### PR TITLE
Converted coffee and hangover scripts to PowerShell

### PR DESCRIPTION
**Pull request by RandomlyKnighted**

### CODE REVIEW

**Comment by RandomlyKnighted** [comment]
***Note:*** I did try to squash the commits that's why you see a duplicate commit titled ```Added fucking_coffee and hangover PowerShell modules```.

**Comment by RandomlyKnighted** [comment]
@NARKOZ is there anything else that I need to do?

**Comment by NARKOZ** [comment]
Could you rebase and squash the commits?

**Comment by RandomlyKnighted** [comment]
I'll give it a shot again. but so far I haven't had any luck with the squashing them.

**Pull request closed without merging**
