### PR TITLE
Implementation for C# - Hangover.cs and SmackMyBitch.cs implementation

### PR DESCRIPTION
**Pull request by destromas1**
## Implementation for C#

Added Hangover.cs and implementation
Added SmackMyBitch.cs and implementation

### CODE REVIEW

**Comment by NARKOZ** [comment]
Can you rename folder to _CSharp_?

**Comment by destromas1** [comment]
@NARKOZ Sure , I am doing right now

**Comment by destromas1** [comment]
@NARKOZ  Done . Please merge!

**Comment by NARKOZ** [comment]
Please squash your commits.

**Comment by destromas1** [comment]
@NARKOZ Please check

**Comment by destromas1** [comment]
@NARKOZ 

Please merge my PR. Thanks!

**Comment by destromas1** [comment]
@NARKOZ 

Squashed,Thanks!

**Comment by Bigamt22** [comment]
- -

**Review by Bigamt22 — COMMENTED** [review]
Jj

**Pull request merged**
